import type { CompanySnapshot, Vertical } from "./types";
import { VERTICAL_LABEL } from "./types";
import { bucketItems, cycleElapsed, healthFor } from "./progress";
import { daysBetween, formatDateTime, formatDue } from "./dates";

// Deterministic "rules" brief. Used when no ANTHROPIC_API_KEY is configured, and
// as the safety net if the model call fails. Pure function -> easy to unit test.
export function buildRulesBrief(s: CompanySnapshot): string {
  const { today } = s;
  const elapsed = cycleElapsed(s.objectives, today);
  const buckets = bucketItems(s.items, today);
  const pendingDecisions = s.decisions.filter((d) => d.status === "pending");
  const urgentDecisions = pendingDecisions.filter((d) => d.deadline && daysBetween(today, d.deadline) <= 2);
  const openBlockers = s.blockers.filter((b) => !b.resolved);
  const founderOverdue = buckets.overdue.filter((i) => i.owner === "Founder");

  const dateLabel = new Date(`${today}T12:00:00Z`).toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  });

  const out: string[] = [];
  out.push(`# Founder Daily Brief — ${dateLabel}`);
  out.push("");
  out.push(
    `**TL;DR:** ${plural(buckets.overdue.length, "overdue follow-up")}, ` +
      `${plural(buckets.dueToday.length, "item")} due today, ` +
      `${plural(pendingDecisions.length, "decision")} waiting on you ` +
      `(${urgentDecisions.length} within 48h), ${plural(openBlockers.length, "open blocker")}.`,
  );
  out.push("");

  out.push("## Needs you today");
  const needs: string[] = [];
  for (const d of urgentDecisions) {
    needs.push(`- **Decide:** ${d.title} — ${formatDue(d.deadline, today).replace("Due", "due")}. Options: ${d.options.join(" / ")}.`);
  }
  for (const i of founderOverdue) {
    needs.push(`- **Overdue (yours):** ${i.title} (${formatDue(i.due_date, today)}).`);
  }
  for (const i of buckets.dueToday.filter((x) => x.owner === "Founder")) {
    needs.push(`- **Due today (yours):** ${i.title}.`);
  }
  out.push(...(needs.length ? needs : ["- Nothing urgent requires you today. 🎉"]));
  out.push("");

  for (const v of ["clinical", "performance", "company"] as Vertical[]) {
    out.push(`## ${VERTICAL_LABEL[v]}`);
    const objectives = s.objectives.filter((o) => o.vertical === v);
    for (const o of objectives) {
      const health = healthFor(o.progress, elapsed);
      out.push(`- OKR · ${o.title}: **${Math.round(o.progress * 100)}%** (${health.replace("-", " ")})`);
    }
    const overdue = buckets.overdue.filter((i) => i.vertical === v);
    for (const i of overdue) out.push(`- Overdue: ${i.title} → ${i.owner} (${formatDue(i.due_date, today)})`);
    const blockers = openBlockers.filter((b) => b.vertical === v);
    for (const b of blockers) out.push(`- Blocker: ${b.title} — ${b.impact} (owner: ${b.owner})`);
    const decisions = pendingDecisions.filter((d) => d.vertical === v && !urgentDecisions.includes(d));
    for (const d of decisions) out.push(`- Pending decision: ${d.title} (${formatDue(d.deadline, today).replace(/^Due/, "due")})`);
    out.push("");
  }

  const upcoming = s.meetings.filter((m) => daysBetween(today, m.starts_at.slice(0, 10)) <= 1);
  out.push("## Meetings today & tomorrow");
  if (upcoming.length === 0) out.push("- No meetings in the next 48h.");
  for (const m of upcoming) {
    out.push(`- ${formatDateTime(m.starts_at)} ET — **${m.title}**${m.prep_notes ? ` · Prep: ${m.prep_notes}` : ""}`);
  }
  out.push("");

  const delegable = s.items.filter((i) => i.owner === "Founder" && i.status !== "done" && i.priority === "p2");
  if (delegable.length) {
    out.push("## Suggested delegations");
    for (const i of delegable) out.push(`- "${i.title}" is low priority — hand it to the EA?`);
    out.push("");
  }

  out.push("_Generated by rules engine (no AI key configured)._");
  return out.join("\n");
}

// Compact, model-friendly view of the snapshot. Keeps the prompt small and stable.
export function snapshotForModel(s: CompanySnapshot) {
  return {
    today: s.today,
    okr_cycle: s.objectives[0]?.cycle ?? null,
    cycle_elapsed_pct: Math.round(cycleElapsed(s.objectives, s.today) * 100),
    objectives: s.objectives.map((o) => ({
      vertical: o.vertical,
      title: o.title,
      owner: o.owner,
      progress_pct: Math.round(o.progress * 100),
      key_results: o.key_results.map((kr) => `${kr.title}: ${kr.current_value}/${kr.target_value} ${kr.metric} (start ${kr.start_value})`),
    })),
    open_action_items: s.items
      .filter((i) => i.status !== "done")
      .map((i) => ({
        title: i.title,
        vertical: i.vertical,
        owner: i.owner,
        due: i.due_date,
        priority: i.priority,
        status: i.status,
        context: i.context,
      })),
    pending_decisions: s.decisions
      .filter((d) => d.status === "pending")
      .map((d) => ({ title: d.title, vertical: d.vertical, deadline: d.deadline, options: d.options, context: d.context })),
    open_blockers: s.blockers.filter((b) => !b.resolved).map((b) => ({ title: b.title, vertical: b.vertical, impact: b.impact, owner: b.owner })),
    upcoming_meetings: s.meetings.map((m) => ({ title: m.title, starts_at_utc: m.starts_at, attendees: m.attendees, prep: m.prep_notes })),
  };
}

function plural(n: number, word: string): string {
  return `${n} ${word}${n === 1 ? "" : "s"}`;
}
