import { getLatestBrief, getSnapshot } from "@/lib/repo";
import { buildRulesBrief } from "@/lib/brief";
import { aiEnabled } from "@/lib/ai";
import { Markdown } from "@/components/Markdown";
import { CopyButton, SubmitButton } from "@/components/ClientButtons";
import { Card, PageHeader } from "@/components/ui";
import { generateBriefAction } from "../actions";

export default async function BriefPage() {
  const latest = await getLatestBrief();
  const markdown = latest?.markdown ?? buildRulesBrief(await getSnapshot());
  const ai = aiEnabled();

  return (
    <>
      <PageHeader
        title="Daily Brief"
        subtitle={
          ai
            ? "Written by Claude from the live company snapshot: OKRs, follow-ups, decisions, blockers and calendar."
            : "Demo mode: generated by the built-in rules engine. Add ANTHROPIC_API_KEY to have Claude write it."
        }
        action={
          <div className="flex gap-2">
            <CopyButton text={markdown} label="Copy for Slack / Notion" />
            <form action={generateBriefAction}>
              <SubmitButton pendingLabel={ai ? "Claude is writing…" : "Generating…"}>Generate fresh brief</SubmitButton>
            </form>
          </div>
        }
      />
      <Card className="mx-auto max-w-3xl p-8">
        <Markdown source={markdown} />
        <div className="mt-8 border-t border-slate-100 pt-4 text-xs text-slate-400">
          {latest
            ? `Generated ${new Date(latest.created_at).toLocaleString("en-US", { timeZone: "America/New_York" })} ET · ${latest.mode === "claude" ? "Claude" : "rules engine"}`
            : "Preview built from current data — click “Generate fresh brief” to save one."}
        </div>
      </Card>
    </>
  );
}
